version: "3"
services:
  web:
    image: f4814n/css-server:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 200M
      restart_policy:
        condition: on-failure
    environment:
      DB_IP: "mongo"
    ports:
      - "3000:3000"
    networks:
      - webnet

  mongo:
    image: mongo:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 600M
      restart_policy:
        condition: on-failure
    command: ["mongod", "--dbpath", "/data/db"]
    volumes:
      - "database:/data/db"
    networks:
      - webnet
  
  monitor:
    image: dockersamples/visualizer:stable
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.05"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webnet

networks:
  webnet:

volumes:
  database:
