version: "3"
services:
  web:
    image: f4814n/css-server:v1.0.3
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.3"
          memory: 200M
      restart_policy:
        condition: on-failure
    environment:
      DB_IP: "mongo"
      KEY_FILE: "/app/key/keyfile"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    volumes:
      - "key:/app/key"

  mongo:
    image: mongo:4.0
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.3"
          memory: 600M
      restart_policy:
        condition: on-failure
    command: ["mongod", "--dbpath", "/data/db"]
    ports:
      - "27017:27017"
    volumes:
      - "database:/data/db"
    networks:
      - webnet
  
  monitor:
    image: dockersamples/visualizer:stable
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.05"
          memory: 50M
      restart_policy:
        condition: on-failure
      placement:
          constraints:
            - node.role == manager
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webnet

networks:
  webnet:

volumes:
  database:
  key:
