name:                CyberSchoolSystem-Server
version:             0.0.0.1
github:              "CyberSchoolSystem/CyberSchoolSystem-Server"
license:             MIT
author:              "Fabian Geiselhart"
maintainer:          ""
copyright:           "2018 CyberSchoolSystem"

# Metadata used when publishing your package
synopsis:            Voting system for the "Schule als Staat" project
category:            Web

description: Please see the README on Github at <https://github.com/CyberSchoolSystem/CyberSchoolSystem-Server#readme>

extra-source-files:
- README.md
- ChangeLog.md

flags:
  noAuth:
    description: Do not include the authentication system
    default: False
    manual: False
  dev:
    description: Use development settings
    default: False
    manual: False

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- text

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Werror

flags:
  noAuth:
    description: Do not include the authentication system
    default: False
    manual: False
  dev:
    description: Use development settings
    default: False
    manual: False

library: # TODO: other-modules
  source-dirs: src
  exposed-modules: Application
  when:
    - condition: flag(noAuth)
      cpp-options: -DNO_AUTH
    - condition: flag(dev)
      cpp-options: -DDEVELOPMENT
  dependencies:
    - aeson
    - bytestring
    - blaze-html
    - containers
    - data-default-class
    - http-conduit
    - persistent
    - persistent-template
    - persistent-mongoDB
    - shakespeare
    - template-haskell
    - time
    - text-show
    - unordered-containers
    - yesod
    - yesod-auth
    - yesod-auth-hashdb
    - yesod-core
    - yesod-form
    - yesod-persistent

executables:
  server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CyberSchoolSystem-Server

tests:
  CyberSchoolSystem-Server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CyberSchoolSystem-Server
